### ISSUE TITLE
Empty files

### ISSUE THREAD

**Issue by JordiSapesPlanas** [Pablito2020/nozoma-fork#7]
Hi ha fitxers com ProductNameVo o ProductDescriptionVo que no tenen res a dins? Es normal?  Intenteu pujar al més aviat possible aquests fitxers si no no puc provar.

**Comment by Pablito2020** [comment]
Si, ho acabo de veure ara, no me diguis perquè al commit eea031566dbb3643c83c77e95948ecefbf04817b van borrar certs arxius de pms. Ara en breus ho arreglem.

Això ha estat resultat del merge, que consti que a la nostra branca funcionava tot correctament.

Salutacions

**Comment by JordiSapesPlanas** [comment]
Hola Pablo, a la vostra branca també he tingut algun problema. Ja m'he suposat que algun problema heu tingut. No passa res. De cara dema tingueu el projecte deployat. Ja sigui la vostre branch o tot junt, pero que funcioni tal i com espereu

**Comment by Pablito2020** [comment]
Acabo de veure que hi havien commits d'altres integrants a la nostra branca, no entenc perquè ni quan han aparegut, lo curiós es que vam deployar diumenge (desde la nostra branca) i funcionava tot correcte. 

Bueno, ara ho arreglem i fem commit.

**Comment by Pablito2020** [comment]
Vale, ja entenem que va passar. 
Ells a la seva branca van eliminar tot el contingut d'alguns arxius de pms (concretament de producte), cosa que, al fer el merge avui, ha fet que s'eliminin a la nostra branca també (ja que git m'ha forçat a fer un merge en local a la meva branca, no podia desde la pull request).

Per tant, el commit responsable és:
22e11b0c9a9a43c02d2a905a59c6c8f9283230f2

Ara fem push amb els nous canvis

**Comment by Pablito2020** [comment]
Ja hem fet merge, que consti que ens fa ràbia ja que havíem provat tots els casos d'integració amb backoffice a mà i sabíem que tot funcionava correctament, però ara amb aquest commit d'última hora i estant amb exàmens no ho hem pogut corroborar.

Ens veiem demà a la validació.
